# Generated by Django 5.2.7 on 2025-11-02 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='feature_images/')),
                ('prompt_text', models.TextField(help_text='Text to include in AI generation prompt')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FaceFeatureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Face Feature Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FaceComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('composite_image', models.ImageField(blank=True, null=True, upload_to='composites/')),
                ('sketch_image', models.ImageField(blank=True, null=True, upload_to='sketches/')),
                ('final_image', models.ImageField(blank=True, null=True, upload_to='final/')),
                ('additional_notes', models.TextField(blank=True)),
                ('selected_features', models.ManyToManyField(to='face_generator.facefeature')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='facefeature',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='face_generator.facefeaturecategory'),
        ),
    ]
