# Generated by Django 5.2.7 on 2026-02-18 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('image_type', models.CharField(choices=[('sketch', 'Initial Sketch'), ('revision', 'Revision'), ('colorized', 'Colorized')], max_length=20)),
                ('image', models.ImageField(upload_to='versions/')),
                ('prompt_used', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='face_generator.facecomposition')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='face_generator.generationversion')),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
    ]
