# Generated by Django 5.2.7 on 2026-02-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_generator', '0002_generationversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='facecomposition',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Optional reference image (CCTV capture, blurry photo, etc.)', null=True, upload_to='references/'),
        ),
        migrations.AddField(
            model_name='facecomposition',
            name='user_prompt',
            field=models.TextField(blank=True, help_text='Free-form user description (extra details not covered by selectors)'),
        ),
    ]
